### ISSUE TITLE
Add automated testing

### ISSUE THREAD

**Issue by zimbatm** [numtide/nixos-remote#5]
**Is your feature request related to a problem? Please describe.**

It's hard to know if the script keeps working after we change it. There might be regressions.

**Describe the solution you'd like**

Some NixOS test spins up new machines and provisions them using nixos-remote.

**Describe alternatives you've considered**

**Additional context**

**Comment by Mic92** [comment]
In the kexec-installer image we just use nixos vms for the most part: https://github.com/nix-community/nixos-images/blob/main/nix/kexec-installer/test.nix
I think this should be good enough for integration testing and faster. I would leave spinning up machines to the terraform module and have this as an example there.

**Comment by zimbatm** [comment]
Fixed in master
