### ISSUE TITLE
Use shellcheck

### ISSUE THREAD

**Issue by Mic92** [numtide/nixos-remote#9]
I found a few bugs just by using shellcheck: https://github.com/numtide/nixos-remote/pull/8/commits/c5bf76c63efdd1043da8fd93ac7a341ba5cb3745
I think this is must for this kind of projects.

**Comment by zimbatm** [comment]
Fixed in master

**Comment by Mic92** [comment]
32ba35c4ee7eaba2bf08507d69133b972e2bccbe
